### ISSUE TITLE
Biased implementation of hashModOrder

### ISSUE THREAD

**Issue by paragonie-scott** [ibm-research/ecdaa#5]
If the output of the hash function is larger than the order of the curve, this will generate a very small value:

https://github.com/ibm-research/ecdaa/blob/c46b3cd4db217dfb6f4a9a71b9fb338a444e0f16/src/main/java/com/ibm/zurich/crypto/BNCurve.java#L341-L350

The consequence of this failure condition is that the random numbers used in EcdaaSign will be biased (i.e. higher bits have a higher probability of being 0). The consequences of this can be [pretty bad](https://crypto.stackexchange.com/a/48379/24405).

----

Earlier this month I published a [protocol review of ECDAA, as used in WebAuthn](https://paragonie.com/blog/2018/08/security-concerns-surrounding-webauthn-don-t-implement-ecdaa-yet). The reliance of random values (rather than deterministic values; see RFC 6979 for historical precedent) was one of the points I was particularly concerned about.

Given that several IBM employees are listed on the [ECDAA spec](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-ecdaa-algorithm-v2.0-id-20180227.html), and this Github repository belongs to the IBM-Research organization, am I correct in believing this implementation to be somewhat official? 

If so, it further highlights the severity of the cited design flaws.

**Comment by manudrijvers** [comment]
Thanks for your comment. This is actually not a problem: we use this hash function as the Fiat-Shamir hash for generalized Schnorr signatures, and you can prove this construction is secure with the standard techniques, even if the hashModOrder output is not perfectly uniform in the order of the curve.

Let's consider a plain Schnorr signature where we have pk = g^sk. We sign by taking r uniform in the curve order q, t = g^r, c = H(t, pk, m), and s = r + c * sk (mod q), and output signature (c, s). We want this to be zero-knowledge, i.e., not leaking any information about sk, and extractable, meaning that we can apply the [forking lemma](https://cseweb.ucsd.edu/~mihir/papers/multisignatures-ccs.pdf) to extract sk from a signature forger. 

Zero-knowledge: we can simulate in the standard way, by taking c uniform in the hash output, s uniform in the curve order, setting t = g^s pk^-c, and programming the [random oracle](https://dl.acm.org/citation.cfm?id=168596). This simulation is distributed equally to real signatures.

Extractability: we use the standard approach to extract from a schnorr signature with the forking lemma. However, due to reducing the hash outputs modulo the curve order, we can have c != c’ but c = c’ (mod q), in which case extraction does not work. However, this probability can be bounded by 1 in the output size of the hash, which is clearly negligible. 

Your remark about the danger of having a biased hash function is a bit misleading as the cited scheme uses the hash function for a completely different purpose, and those attacks do not apply here.

**Comment by manudrijvers** [comment]
I'll go ahead and close this issue now, but feel free to reopen if you have further questions.
